name: Deploy nodejscicddockerhub
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Image from Docker Hub
        run: docker pull hakilpro/bareminsimumnode-backend:latest

      - name: Delete Old Container
        run: |
          if [ $(docker ps -aq -f name=hakilpro/bareminsimumnode-backend) ]; then
            docker rm -f hakilpro/bareminsimumnode-backend
          fi

      - name: Run Docker Container yes
        run: docker run -d -p 8000:8000 --name bareminsimumnode-backend-container -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" hakilpro/bareminsimumnode-backend:latest
